trigger:
  - '*'

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm install
    npm run build
  displayName: 'npm install and build'

- powershell: |
    Write-Host ' - - - - - - - - - - - - - - - - - - - - - - - - -'
    Write-Host ' reflect Azure Devops repo changes to GitHub repo'
    Write-Host ' - - - - - - - - - - - - - - - - - - - - - - - - - '

    $stageDir = '$(Build.SourcesDirectory)' | Split-Path
    $githubDir = $stageDir +"\"+"gitHub"
    $destination = $githubDir +"\"+"Master.git"
    Write-Host "Build Started By: $(Build.RequestedFor)"
    git config --global user.email "jtblackk@clemson.edu"
    git config --global user.name "jtblackk"
    $sourceURL = 'https://dev.azure.com/S21-VanScoysBoys11-Black-McLendon-OReilly-Griffith/S21-VanScoysBoys11-Black.McLendon.OReilly.Griffith.Pugmire/_git/Master'
    $destURL = 'https://' + ${env:MAPPED_ENV_PAT} + '@github.com/jtblackk/driver-incentive-frontend.git'

    #Check if the parent directory exists and delete
    if((Test-Path -path $githubDir))
    {
      Remove-Item -Path $githubDir -Recurse -force
    }

    if(!(Test-Path -path $githubDir))
    {
      New-Item -ItemType directory -Path $githubDir
      Set-Location $githubDir
      git clone --mirror $sourceURL
    }
    else
    {
      Write-Host "The given folder path $githubDir already exists";
    }

    Set-Location $destination

    Write-Output '*****Git removing remote secondary****'
    git remote rm secondary

    Write-Output '*****Git remote add****'
    git remote add --mirror=fetch secondary $destURL

    Write-Output '*****Git fetch origin****'
    git fetch $sourceURL

    Write-Output '*****Git push secondary****'
    git push secondary --all

    Write-Output '**Azure Devops repo synced with Github repo**'
    Set-Location $stageDir

    if((Test-Path -path $githubDir))
    {
      Remove-Item -Path $githubDir -Recurse -force
    }

  env:
    MAPPED_ENV_PAT: $(GithubAcc.PAT)


